//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartments
    {
        public Apartments()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id { get; set; }
        public int BuildingNumber { get; set; }
        public int ApartmentNumber { get; set; }
        public Nullable<int> Rooms { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
